version: '3'
services:
  web:
    # build: .
    image: streamlitapp
    container_name: streamlitapp
    ports:
      - "8502:8501"
    # depends_on:
    #   - db
    networks:
      - streamlit_net
    volumes:
      - ./main.py:/app/main.py
      - ./pages/:/app/pages/
  # db:
  #   container_name: myslq2
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: mydatabase
    # env_file: 
    #   - ./env_file.env
    # ports:
    #   - "3306:3306"
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # networks:
    #   - streamlit_net

networks:
  streamlit_net:
    driver: bridge